---
- name: Prepare Bash profile
  template:
    dest: "/home/{{ item.user }}/.bash_profile"
    src: ".bash_profile.j2"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items: "{{ informatica.users }}"
  become: yes

- name: Create directories 1/2
  file:
    state: directory
    dest: "{{ informatica.base_directory }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 0700
  become: yes

- name: Create directories 1/2
  file:
    state: directory
    dest: "{{ informatica_root_directory }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 0700
  become: yes


- name: Create directories 1/2
  file:
    state: directory
    dest: "{{ informatica_directory }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 0700
  become: yes

- name: Create directories 2/2
  file:
    state: directory
    dest: "{{ informatica_install_directory }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 755
  become: yes

- name: Copy license key to "{{ informatica_directory }}"
  copy:
    src: "{{ informatica.key_file }}"
    dest: "{{ informatica_directory }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 0644
    remote_src: yes
  become: yes

- name: Extract the installer placed in "{{ informatica_directory }}"
  unarchive:
    src: "{{ informatica.archive }}"
    dest: "{{ informatica_directory }}"
    copy: no
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
  become: yes
