---
- name: "Modify the attached silent installer template and Copy prepared SilentInput.properties files to {{ informatica_directory }}"
  template:
    src: "{{ informatica.silentinput_properties_file }}"
    dest: "{{ informatica_directory }}/SilentInput.properties"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    mode: 0644
    remote_src: yes
  become: yes

- name: "Update permissions"
  file:
    path: "{{ item }}"
    owner: "{{ informatica.owner }}"
    group: "{{ informatica.group }}"
    state: directory
    recurse: yes
    mode: "o-rx"
  with_items:
    - "{{ informatica.base_directory }}"

- name: "Run  silentinstall.sh from {{ informatica_directory }}"
  shell: ./silentinstall.sh
  args:
    chdir: "{{ informatica_directory }}"
  environment:
  - IATEMPDIR: "{{ informatica_temp_directory }}"
  become: yes
